# Generated by Django 4.1.2 on 2022-10-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('icao_sign', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_fueling', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('registry', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aircraft_type', models.CharField(max_length=10)),
                ('cruising_speed', models.IntegerField()),
                ('operational_weight', models.IntegerField()),
                ('max_takeoff_weight', models.IntegerField()),
                ('max_fuel', models.IntegerField()),
                ('fuel_burn', models.IntegerField()),
                ('fuel_unit', models.CharField(max_length=10)),
            ],
        ),
    ]
