# Generated by Django 4.1.2 on 2022-10-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aerodrome',
            new_name='Airport',
        ),
    ]
