# Generated by Django 4.1.2 on 2022-10-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_planner', '0002_rename_aerodrome_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fuel_unit',
            field=models.CharField(choices=[('LB', 'pounds'), ('KG', 'kilograms')], max_length=2),
        ),
    ]
